//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Convenio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Convenio()
        {
            this.Progreso = new HashSet<Progreso>();
        }
    
        public int con_iCodigo { get; set; }
        public Nullable<int> est_iCodigo { get; set; }
        public Nullable<int> cpr_iCodigo { get; set; }
        public Nullable<int> emp_iCodigo { get; set; }
        public Nullable<System.DateTime> con_dtFechaInicio { get; set; }
        public Nullable<System.DateTime> con_dtFechaFin { get; set; }
        public string con_vcPuesto { get; set; }
    
        public virtual CoordinadorPracticas CoordinadorPracticas { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Estudiante Estudiante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Progreso> Progreso { get; set; }
    }
}
