//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSProyecto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModels : DbContext
    {
        public DBModels()
            : base("name=DBModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<AsistenteEmpresa> AsistenteEmpresa { get; set; }
        public virtual DbSet<Competencia> Competencia { get; set; }
        public virtual DbSet<ContribucionEquipo> ContribucionEquipo { get; set; }
        public virtual DbSet<Convenio> Convenio { get; set; }
        public virtual DbSet<CoordinadorPracticas> CoordinadorPracticas { get; set; }
        public virtual DbSet<Desafio> Desafio { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Escuela> Escuela { get; set; }
        public virtual DbSet<Estudiante> Estudiante { get; set; }
        public virtual DbSet<Evaluacion> Evaluacion { get; set; }
        public virtual DbSet<Incidencia> Incidencia { get; set; }
        public virtual DbSet<InformeDesempeno> InformeDesempeno { get; set; }
        public virtual DbSet<InformePractica> InformePractica { get; set; }
        public virtual DbSet<Logro> Logro { get; set; }
        public virtual DbSet<Objetivo> Objetivo { get; set; }
        public virtual DbSet<Progreso> Progreso { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
