//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public int est_iCodigo { get; set; }
        public Nullable<int> con_iCodigo { get; set; }
        public Nullable<int> usu_iCodigo { get; set; }
        public string est_vcCodigo { get; set; }
        public string est_vcCorreo { get; set; }
        public Nullable<int> esc_iCodigo { get; set; }
    
        public virtual Convenio Convenio { get; set; }
        public virtual Escuela Escuela { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
