//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluacion
    {
        public int eva_iCodigo { get; set; }
        public Nullable<int> ase_iCodigo { get; set; }
        public Nullable<int> pro_iCodigo { get; set; }
        public string eva_vcDescripcion { get; set; }
    
        public virtual AsistenteEmpresa AsistenteEmpresa { get; set; }
        public virtual Progreso Progreso { get; set; }
    }
}
