//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidencia
    {
        public int inc_iCodigo { get; set; }
        public Nullable<int> adm_iCodigo { get; set; }
        public string inc_txDescripcion { get; set; }

        private string nombre;

        public string Nombre
        {
            get
            {
                using(DBModels contexto = new DBModels())
                {
                    Administrador administrador = contexto.Administrador.Find(adm_iCodigo);
                    Usuario usuario = contexto.Usuario.Find(administrador.usu_iCodigo);
                    nombre = usuario.usu_vcNombres + " " + usuario.usu_vcApellidos;
                    return nombre;
                }
            }
            set
            {
                nombre = value;
            }
        }




        public virtual Administrador Administrador { get; set; }
    }
}
