//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeDesempeno
    {
        public int ind_iCodigo { get; set; }
        public Nullable<int> cpr_iCodigo { get; set; }
        public string ind_vcContenido { get; set; }
        public Nullable<System.DateTime> ind_dtFechaRevision { get; set; }
    
        public virtual CoordinadorPracticas CoordinadorPracticas { get; set; }
    }
}
