//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objetivo
    {
        public int obj_iCodigo { get; set; }
        public Nullable<int> est_iCodigo { get; set; }
        public string obj_vcDescripcion { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
    }
}
