//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progreso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Progreso()
        {
            this.Evaluacion = new HashSet<Evaluacion>();
        }
    
        public int pro_iCodigo { get; set; }
        public Nullable<int> con_iCodigo { get; set; }
        public string pro_vcDetalles { get; set; }
        public Nullable<System.DateTime> pro_dtFechaActualizacion { get; set; }
    
        public virtual Convenio Convenio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluacion> Evaluacion { get; set; }
    }
}
