//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progreso
    {
        public int pro_iCodigo { get; set; }
        public Nullable<int> con_iCodigo { get; set; }
        public Nullable<int> eva_iCodigo { get; set; }
        public string pro_vcDetalles { get; set; }
        public Nullable<System.DateTime> pro_dtFechaActualizacion { get; set; }
    
        public virtual Convenio Convenio { get; set; }
    }
}
