//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int tar_iCodigo { get; set; }
        public Nullable<int> est_iCodigo { get; set; }
        public string tar_vcDescripcion { get; set; }
        public string tar_vcNotaObtenida { get; set; }

        public string nombre;
        public string Nombre
        {
            get
            {
                using (DBModels contexto = new DBModels())
                {
                    Estudiante estudiante = contexto.Estudiante.Find(est_iCodigo);
                    if(estudiante != null)
                    {
                        Usuario usuario = contexto.Usuario.Find(estudiante.usu_iCodigo);
                        return usuario.usu_vcNombres;
                    }
                    return null;
                }
                
            }
            set
            {
                nombre = value;
            }
        }
        public string apellido;
        public string Apellido
        {
            get
            {
                using (DBModels contexto = new DBModels())
                {
                    Estudiante estudiante = contexto.Estudiante.Find(est_iCodigo);
                    if(estudiante != null)
                    {
                        Usuario usuario = contexto.Usuario.Find(estudiante.usu_iCodigo);
                        return usuario.usu_vcApellidos;
                    }
                    return null; 
                }

            }
            set
            {
                apellido = value;
            }
        }
        public virtual Estudiante Estudiante { get; set; }
    }
}
