//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPSProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int tar_iCodigo { get; set; }
        public Nullable<int> eva_iCodigo { get; set; }
        public string tar_vcDescripcion { get; set; }
        public Nullable<int> tar_iNotaObtenida { get; set; }
    
        public virtual Evaluacion Evaluacion { get; set; }
    }
}
